### ISSUE TITLE
VIRUS ALERT!!!! I sincerely hope you're not doing anything shady!

### ISSUE THREAD

**Issue by shin-illua** [CherryPill/system_info#73]
https://www.virustotal.com/gui/file/bdf157e1c8fbf32a5f2ddbe968d3809ed33758a262a82201d9ede4f8f802a317/detection
An explanation would not hurt!

**Comment by CherryPill** [comment]
Now that's a surprise, I really have no concrete explanation for you at this time, but it's definitely a false positive and caused by using some unsafe Win32 API data structures. This problem also seems to affect versions 1.4.x, not 1.3.x. 

I can assure you that all the application does with your system is read the WMI tables, saves and reads hardware data to/from your hard disk, temporarily saves the screenshot to your appdata folder and then deletes it afterwards and that's it. The source code is free for you to explore and compile on your own using MSVC. 

I'll see what I can do about this problem, but if you're really paranoid about security or have difficulty navigating the source code and identifying security flaws I suggest you use 1.3.x versions.

**Comment by shin-illua** [comment]
First, sorry for the clickbaity title, I have to do it so that people would be aware about this issue, and I believe that it wouldn't hurt the image of the project at all given the labels added and the fact that I doubt anyone seeing that title wouldn't click and find out more. 

Second, I'll try and build the solution in my machine and see if I could produce the same issue on the output binaries, and will also conduct additional analysis to give more insight about this issue.

**Comment by CherryPill** [comment]
Ok, so I build 1.4.2 locally and get at most 4 detection hits.

https://www.virustotal.com/gui/file/98b98d9e0793c21d366f75d3decab6e64bc15b8c147fd9251b05c47c41390cbf/detection

if I rescan the executable from your link I get different hit counts every time, from 16 to 25. 

This is all very strange. I guess I'm gonna have to dig through the source code and fire fight parts of the code that could set off the AV.

**Comment by CherryPill** [comment]
So after a few hours of checking source code and messing around with virus total I can say that all of this is caused by the fact that the executable **isn't digitally signed**, because I started getting hits from virus total on version 1.3.x. I'll see about self-signing the executable, but the certificate is most likely not cheap, so for the time being it's going to be a false positive on virus total and other online AV checking tools. 

Have you ever encountered the executable being flagged as false positive with your local AV software or is it just the virus total?
